"""Pydantic models for the multi-agent investigation cycle."""

from __future__ import annotations

import enum
from datetime import datetime

from pydantic import BaseModel, Field


class InvestigationPriority(enum.StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class FindingStatus(enum.StrEnum):
    CONFIRMED = "confirmed"
    DISPROVEN = "disproven"
    INCONCLUSIVE = "inconclusive"


class InvestigationTopic(BaseModel):
    """A focused topic for an investigator agent to examine."""

    title: str
    dimension: str
    dimension_value: str
    metrics: list[str] = Field(default_factory=list)
    question: str
    priority: InvestigationPriority = InvestigationPriority.MEDIUM
    context: str = ""


class Hypothesis(BaseModel):
    """An untested hypothesis generated by the investigator."""

    topic_title: str
    statement: str
    reasoning: str
    created_at: datetime
    run_id: str = ""


class Finding(BaseModel):
    """An ML-tested finding with evidence."""

    topic_title: str
    statement: str
    status: FindingStatus
    evidence: list[str] = Field(default_factory=list)
    metrics_cited: dict[str, float] = Field(default_factory=dict)
    created_at: datetime
    run_id: str = ""
    tool_use_failed: bool = False


class CircuitBreakerBudget(BaseModel):
    """Budget limits for the investigation cycle."""

    max_iterations: int = 5
    max_tokens: int = 100_000
    max_seconds: int = 300
    max_spend_usd: float = 10.00


class GeneratedDocument(BaseModel):
    """A plain-language document produced by the synthesizer."""

    title: str
    content: str
    document_type: str
    run_id: str
    created_at: datetime


class AnalyticalStrategy(BaseModel):
    """A generalized investigation approach derived from findings."""

    trigger: str  # "when you see X"
    action: str  # "investigate Y"
    derived_from: list[str] = Field(default_factory=list)  # finding references
    created_at: datetime
